INSERT INTO "ANIMALS" ("NAME", "TYPE") VALUES ('King of king PREFIX', 'lion');
INSERT INTO "ANIMALS" ("NAME", "TYPE") VALUES ('ourazi PREFIX', 'horse');

INSERT INTO "PERSONS" ("NAME", "AGE") VALUES ('Daniel PREFIX', 21);
INSERT INTO "PERSONS" ("NAME", "AGE") VALUES ('Emile PREFIX', 31);
